#!/bin/bash
rest=$HOME/GitHub/visbo-server-rest
predictkm=$HOME/GitHub/predictkm
// if prediction is installed update it
if test -d "$predictkm"; then
  cd $predictkm
  echo "01 Predict: Checking Local Status of Branch"
  git status
  if [ $? -ne 0 ]
  then
    echo "Predict: FATAL: Local Changes have to be checked first before upgrading."
    exit 1
  fi

  echo "02 Predict: Pull Branch from Repository Server"
  pullOutput=`git pull`
  if [ $? -ne 0 ]
  then
    echo "FATAL Predict: Pull Failed to update Predict Branch."
    exit 1
  fi
fi

cd $rest
continueOnEmptyPull=0
if [ $# -gt 0 -a "$1" = "force" ]
then
  continueOnEmptyPull=1
fi
echo "01: Checking Local Status of Branch"
git status
if [ $? -ne 0 ]
then
  echo "FATAL: Local Changes have to be checked first before upgrading."
  exit 1
fi

echo "02: Pull Branch from Repository Server"
updateCmdOrg=`date -r update-rest '+%Y-%m-%dT%H:%M:%S'`
updatePackageOrg=`date -r package.json '+%Y-%m-%dT%H:%M:%S'`
pullOutput=`git pull`
if [ $? -ne 0 ]
then
  echo "FATAL: Pull Failed to update ReST Server Branch."
  exit 1
fi

echo "Pull Result"
echo "$pullOutput"
if [ "$continueOnEmptyPull" -eq 0 -a "$pullOutput" = "Already up to date." ]
then
  echo "INFO: No changes in the ReST Server Branch."
  exit 0
fi

updateCmdAct=`date -r update-rest '+%Y-%m-%dT%H:%M:%S'`
if [ "$updateCmdOrg" != "$updateCmdAct" ]
then
  echo "INFO: Update Script has changed in between, restart update again."
  update-rest force
  exit $?
fi

nodeversion=$rest/nodeversion
# if nodeversion exists, check that it is the active one
if test -f "$nodeversion"; then
  eval `cat $nodeversion`
  echo "INFO: verify that node version is installed" $NODE_VERSION
  n $NODE_VERSION
fi

updatePackageAct=`date -r package.json '+%Y-%m-%dT%H:%M:%S'`
if [ "$updatePackageOrg" != "$updatePackageAct" ]
then
  echo "03: Install subcomponents from NODE environment"
  npm install
  if [ $? -ne 0 ]
  then
    echo "FATAL: Install of NODE components failed."
    exit 1
  fi
fi

echo "04: Update API Documentation"
apidoc -i routes -o public/apidoc
rm -rf /var/www/apidoc/*
cp -r public/apidoc/* /var/www/apidoc
find /var/www/apidoc -type d -exec chmod 755 {} +
find /var/www/apidoc -type f -exec chmod 644 {} +

echo "05: Run Upgrade Script against DB"
# get the DB Connection string
if [ -f update-db.js ]; then
    echo `date` "Upgrade Script Found!"
    CONF=`grep '^ *NODE_VISBODB' .env`
    eval $CONF
    mongo --quiet "$NODE_VISBODB" update-db.js | grep --invert "I NETWORK"
    if [ $? -ne 0 ]
    then
      echo "FATAL: Database Update Script Failed."
      exit 1
    fi
    echo `date` "Upgrade Script Executed & Finished"
else
  echo "No Upgrade Script available!"
fi

echo "06: Manage NODE Process with PM2"
pm2 list
pm2 restart VisboReST
if [ $? -ne 0 ]
then
  echo "FATAL: PM2 Restart failed to Restart Visbo-Server-Rest."
  exit 1
fi
pm2 reset VisboReST

echo "ReST Server Updated Successfully"
